language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
sudo: false
script:
  - python setup.py test
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never